// <auto-generated />
using System;
using DossierAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DossierAPI.Migrations
{
    [DbContext(typeof(DossierDbContext))]
    [Migration("20231114162440_DossierModel")]
    partial class DossierModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("DossierAPI.Models.Dossier", b =>
                {
                    b.Property<int>("DossierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateArrivee")
                        .HasColumnType("TEXT");

                    b.Property<int>("DureeSejourJours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroVol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeVoyageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DossierId");

                    b.ToTable("Dossiers");
                });

            modelBuilder.Entity("DossierAPI.Models.TypeVoyage", b =>
                {
                    b.Property<int>("TypeVoyageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TypeVoyageId");

                    b.ToTable("TypeVoyages");
                });
#pragma warning restore 612, 618
        }
    }
}
